Section C: Q1. Create one executed notebook in local Jupyter or Colab. Use the dataset below or recreate it as a CSV named week_2_3_exam_student_signals.csv.

---
Ans: Creating the CSV steps:

1. Import `pandas` library for data manipulation and analysis, aliased as `pd` for easy usage.
2. Import `files` module from google colab for downloading files.
3. Create a dictionary named `data` which holds lists which represent columns of the data. The dictionary represents raw input for our data frame.
4. Convert the data dictionary into a pandas data frame and assign variable `df`.
5. Save the data frame `df` to a CSV file.
6. Print a confirmation line that the CSV is created without any errors.
7. Download the newly created CSV file into your local machine directly from google colab env.

In [ ]:
import pandas as pd
from google.colab import files

data = {
    'Student_ID':['2026CS001', '2026CS002', '2026IT001', '2026IT002', '2026CE001', '2026CE002', '2026CS003', '2026IT003'],
    'Student_Name': ['Aditi', 'Bhavana', 'Chaitra', 'Divya', 'Eesha', 'Fatima', 'Gauri', 'Harshada'],
    'Student_Department':['CS','CS','IT','IT','CE','CE','CS','IT'],
    'Attendance_Pct':[92, 64, 78, 55, 88, 71, 96, 43],
    'Diary_Entries':[12, 6, 9, 4, 10, 8, 14, 2],
    'Tasks_Completed':[8, 5, 7, 3, 8, 6, 9, 2],
    'Assignment_Score': [84, 58, 72, 46, 79, 66, 91, 35],
    'Lab_Score': [88, 61, 76, 52, 82, 69, 94, 41]
}

df = pd.DataFrame(data)
df.to_csv('week_2_3_exam_student_signals.csv', index=False)

print("CSV created!")
files.download('week_2_3_exam_student_signals.csv')

CSV created!

Q1.1 Create or load the dataset and display the first rows.


---
Ans: Displaying the first rows:

    1. Display a text "First rows:" as a label.
    2. Use the method `df.head()` to display the first 5 rows of the data frame.

In [ ]:
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,Student_ID,Student_Name,Student_Department,Attendance_Pct,Diary_Entries,Tasks_Completed,Assignment_Score,Lab_Score
0,2026CS001,Aditi,CS,92,12,8,84,88
1,2026CS002,Bhavana,CS,64,6,5,58,61
2,2026IT001,Chaitra,IT,78,9,7,72,76
3,2026IT002,Divya,IT,55,4,3,46,52
4,2026CE001,Eesha,CE,88,10,8,79,82

Q1.2. Check data types, missing values, and basic shape.


---
Ans: Checking data types, missing values and basic shape:

1. Use `df.shape` to display the dimension of the data frame. This returns a tuple representing the number of rows and columns.
2. Display the data types of each column using `df.dtypes`.
3. Check for missing values using `df.isunll().sum()` method.
4. Generate descriptive statistics for all numerical columns in the data frame using `df.describe()` method. The descriptives are: `count`, `mean`, `std`, `min`, `meadian`, `max`

In [ ]:
print("Shape of dataset:", df.shape)
print("\nData types:")
print(df.dtypes)
print("\nMissing values per column:")
print(df.isnull().sum())
print("\nBasic statistics:")
df.describe()

Shape of dataset: (8, 8)

Data types:
Student_ID            object
Student_Name          object
Student_Department    object
Attendance_Pct         int64
Diary_Entries          int64
Tasks_Completed        int64
Assignment_Score       int64
Lab_Score              int64
dtype: object

Missing values per column:
Student_ID            0
Student_Name          0
Student_Department    0
Attendance_Pct        0
Diary_Entries         0
Tasks_Completed       0
Assignment_Score      0
Lab_Score             0
dtype: int64

Basic statistics:

,Attendance_Pct,Diary_Entries,Tasks_Completed,Assignment_Score,Lab_Score
count,8.000000,8.000000,8.000000,8.000000,8.000000
mean,73.375000,8.125000,6.000000,66.375000,70.375000
std,18.700172,4.015595,2.507133,19.190306,18.228216
min,43.000000,2.000000,2.000000,35.000000,41.000000
25%,61.750000,5.500000,4.500000,55.000000,58.750000
50%,74.500000,8.500000,6.500000,69.000000,72.500000
75%,89.000000,10.500000,8.000000,80.250000,83.500000
max,96.000000,14.000000,9.000000,91.000000,94.000000

Q1.3. Create a function that calculates final readiness score from attendance, diary, task, assignment, and lab signals.

---
Ans: Calculate final readiness of students:
1. Define a function named `calculate_readiness_score` taking five inputs: `attendance`, `diary`, `tasks`, `assignment_score` and `lab_score`.
2. Scale each of the inputs and add them together and store the value after rounding it up be two decimals in `total` variable.
3. Apply this function to every row in the data frame and create a new column `readiness_score` which stores the readiness score of each student.

In [ ]:
def calculate_readiness_score(attendance, diary, tasks, assignment, lab):

    attendance_score  = (attendance / 100) * 25
    diary_score       = (diary / 15)  * 20
    task_score        = (tasks / 10)  * 20
    assignment_score  = (assignment / 100) * 20
    lab_score         = (lab / 100)  * 15

    total = attendance_score + diary_score + task_score + assignment_score + lab_score
    return round(total, 2)

df['Readiness_Score'] = df.apply(
    lambda row: calculate_readiness_score(
        row['Attendance_Pct'],
        row['Diary_Entries'],
        row['Tasks_Completed'],
        row['Assignment_Score'],
        row['Lab_Score']
    ), axis=1
)

print("Readiness scores calculated:")
df[['Student_Name', 'Readiness_Score']]

Readiness scores calculated:

  Student_Name  Readiness_Score
0        Aditi            85.00
1      Bhavana            54.75
2      Chaitra            71.30
3        Divya            42.08
4        Eesha            79.43
5       Fatima            63.97
6        Gauri            92.97
7     Harshada            30.57

Q1.4. Use loops or apply logic to classify each student into Support, Developing, Strong, or Excellent.

---
Ans: Classifying each student:

1. Deine a function `classify_student` to categorize students.
2. Using the readiness_score of students, categorize all the students into 'Excellent', 'Strong', 'Developing', 'Support'.
3.  The function creates a new column in the data frame as `performance_band`.

In [ ]:
def classify_student(score):
    if score >= 80:
        return 'Excellent'
    elif score >= 65:
        return 'Strong'
    elif score >= 50:
        return 'Developing'
    else:
        return 'Support'

bands = []
for score in df['Readiness_Score']:
    bands.append(classify_student(score))

df['Performance_Band'] = bands

print("Students with performance bands:")
df[['Student_Name', 'Student_Department', 'Readiness_Score', 'Performance_Band']]

Students with performance bands:

  Student_Name Student_Department  Readiness_Score Performance_Band
0        Aditi                 CS            85.00        Excellent
1      Bhavana                 CS            54.75       Developing
2      Chaitra                 IT            71.30           Strong
3        Divya                 IT            42.08          Support
4        Eesha                 CE            79.43           Strong
5       Fatima                 CE            63.97       Developing
6        Gauri                 CS            92.97        Excellent
7     Harshada                 IT            30.57          Support

Q1.5. Generate at least three analytics outputs: department average, top performer, and students needing support.


---
Ans: Analytical Outputs:

1. Calculate and print the average readiness score for each department.
2. Identify and print the details of single top performing student across all departments based on their readiness score.
3. Filter and print the names, departments and readiness scores of all students who have been classified as 'Support' performance band.

In [ ]:

print("=== Department Average Readiness Score ===")
dept_avg = df.groupby('Student_Department')['Readiness_Score'].mean().round(2)
print(dept_avg)


print("\n=== Top Performer ===")
top = df.loc[df['Readiness_Score'].idxmax()]
print(f"Name       : {top['Student_Name']}")
print(f"Department : {top['Student_Department']}")
print(f"Score      : {top['Readiness_Score']}")
print(f"Band       : {top['Performance_Band']}")


print("\n=== Students Needing Support ===")
support_students = df[df['Performance_Band'] == 'Support'][
    ['Student_Name', 'Student_Department', 'Readiness_Score']
]
print(support_students.to_string(index=False))

=== Department Average Readiness Score ===
Student_Department
CE    71.70
CS    77.57
IT    47.98
Name: Readiness_Score, dtype: float64

=== Top Performer ===
Name       : Gauri
Department : CS
Score      : 92.97
Band       : Excellent

=== Students Needing Support ===
Student_Name Student_Department  Readiness_Score
       Divya                 IT            42.08
    Harshada                 IT            30.57